"""empty message

Revision ID: 674f1ae92c72
Revises: None
Create Date: 2016-04-30 01:25:50.068419

"""

# revision identifiers, used by Alembic.
revision = '674f1ae92c72'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'profile_userid_fkey', 'profile', type_='foreignkey')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(u'profile_userid_fkey', 'profile', 'user', ['userid'], ['id'])
    ### end Alembic commands ###
